//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebServer
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class VendasEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto VendasEntities usando a cadeia de conexão localizada na seção 'VendasEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public VendasEntities() : base("name=VendasEntities", "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto VendasEntities.
        /// </summary>
        public VendasEntities(string connectionString) : base(connectionString, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto VendasEntities.
        /// </summary>
        public VendasEntities(EntityConnection connection) : base(connection, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Cliente. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Cliente.
        /// </summary>
        /// <param name="idCliente">Valor inicial da propriedade IdCliente.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="dataNasc">Valor inicial da propriedade DataNasc.</param>
        /// <param name="renda">Valor inicial da propriedade Renda.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nome, global::System.DateTime dataNasc, global::System.Decimal renda)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.Nome = nome;
            cliente.DataNasc = dataNasc;
            cliente.Renda = renda;
            return cliente;
        }

        #endregion
        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNasc
        {
            get
            {
                return _DataNasc;
            }
            set
            {
                OnDataNascChanging(value);
                ReportPropertyChanging("DataNasc");
                _DataNasc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNasc");
                OnDataNascChanged();
            }
        }
        private global::System.DateTime _DataNasc;
        partial void OnDataNascChanging(global::System.DateTime value);
        partial void OnDataNascChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Renda
        {
            get
            {
                return _Renda;
            }
            set
            {
                OnRendaChanging(value);
                ReportPropertyChanging("Renda");
                _Renda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Renda");
                OnRendaChanged();
            }
        }
        private global::System.Decimal _Renda;
        partial void OnRendaChanging(global::System.Decimal value);
        partial void OnRendaChanged();

        #endregion
    
    }

    #endregion
    
}
