//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadados de Relação EDM

[assembly: EdmRelationshipAttribute("VendasModel", "FK_Produto_Categoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UsandoEntityFramework4.Categoria), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UsandoEntityFramework4.Produto), true)]

#endregion

namespace UsandoEntityFramework4
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class VendasEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto VendasEntities usando a cadeia de conexão localizada na seção 'VendasEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public VendasEntities() : base("name=VendasEntities", "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto VendasEntities.
        /// </summary>
        public VendasEntities(string connectionString) : base(connectionString, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto VendasEntities.
        /// </summary>
        public VendasEntities(EntityConnection connection) : base(connection, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Categoria> Categorias
        {
            get
            {
                if ((_Categorias == null))
                {
                    _Categorias = base.CreateObjectSet<Categoria>("Categorias");
                }
                return _Categorias;
            }
        }
        private ObjectSet<Categoria> _Categorias;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Produto> Produtos
        {
            get
            {
                if ((_Produtos == null))
                {
                    _Produtos = base.CreateObjectSet<Produto>("Produtos");
                }
                return _Produtos;
            }
        }
        private ObjectSet<Produto> _Produtos;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Categorias. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToCategorias(Categoria categoria)
        {
            base.AddObject("Categorias", categoria);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Produtos. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToProdutos(Produto produto)
        {
            base.AddObject("Produtos", produto);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Clientes. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Categoria.
        /// </summary>
        /// <param name="idCategoria">Valor inicial da propriedade IdCategoria.</param>
        /// <param name="descricao">Valor inicial da propriedade Descricao.</param>
        public static Categoria CreateCategoria(global::System.Int32 idCategoria, global::System.String descricao)
        {
            Categoria categoria = new Categoria();
            categoria.IdCategoria = idCategoria;
            categoria.Descricao = descricao;
            return categoria;
        }

        #endregion
        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategoria
        {
            get
            {
                return _IdCategoria;
            }
            set
            {
                if (_IdCategoria != value)
                {
                    OnIdCategoriaChanging(value);
                    ReportPropertyChanging("IdCategoria");
                    _IdCategoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCategoria");
                    OnIdCategoriaChanged();
                }
            }
        }
        private global::System.Int32 _IdCategoria;
        partial void OnIdCategoriaChanging(global::System.Int32 value);
        partial void OnIdCategoriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Produto_Categoria", "Produto")]
        public EntityCollection<Produto> Produtos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produto>("VendasModel.FK_Produto_Categoria", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produto>("VendasModel.FK_Produto_Categoria", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Cliente.
        /// </summary>
        /// <param name="idCliente">Valor inicial da propriedade IdCliente.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="email">Valor inicial da propriedade Email.</param>
        /// <param name="telefone">Valor inicial da propriedade Telefone.</param>
        /// <param name="cidade">Valor inicial da propriedade Cidade.</param>
        /// <param name="estado">Valor inicial da propriedade Estado.</param>
        /// <param name="dataNascimento">Valor inicial da propriedade DataNascimento.</param>
        /// <param name="limiteCredito">Valor inicial da propriedade LimiteCredito.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nome, global::System.String email, global::System.String telefone, global::System.String cidade, global::System.String estado, global::System.DateTime dataNascimento, global::System.Decimal limiteCredito)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.Nome = nome;
            cliente.Email = email;
            cliente.Telefone = telefone;
            cliente.Cidade = cidade;
            cliente.Estado = estado;
            cliente.DataNascimento = dataNascimento;
            cliente.LimiteCredito = limiteCredito;
            return cliente;
        }

        #endregion
        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LimiteCredito
        {
            get
            {
                return _LimiteCredito;
            }
            set
            {
                OnLimiteCreditoChanging(value);
                ReportPropertyChanging("LimiteCredito");
                _LimiteCredito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimiteCredito");
                OnLimiteCreditoChanged();
            }
        }
        private global::System.Decimal _LimiteCredito;
        partial void OnLimiteCreditoChanging(global::System.Decimal value);
        partial void OnLimiteCreditoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Produto.
        /// </summary>
        /// <param name="idProduto">Valor inicial da propriedade IdProduto.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="preco">Valor inicial da propriedade Preco.</param>
        /// <param name="dataCadastro">Valor inicial da propriedade DataCadastro.</param>
        /// <param name="idCategoria">Valor inicial da propriedade IdCategoria.</param>
        public static Produto CreateProduto(global::System.Int32 idProduto, global::System.String nome, global::System.Decimal preco, global::System.DateTime dataCadastro, global::System.Int32 idCategoria)
        {
            Produto produto = new Produto();
            produto.IdProduto = idProduto;
            produto.Nome = nome;
            produto.Preco = preco;
            produto.DataCadastro = dataCadastro;
            produto.IdCategoria = idCategoria;
            return produto;
        }

        #endregion
        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategoria
        {
            get
            {
                return _IdCategoria;
            }
            set
            {
                OnIdCategoriaChanging(value);
                ReportPropertyChanging("IdCategoria");
                _IdCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCategoria");
                OnIdCategoriaChanged();
            }
        }
        private global::System.Int32 _IdCategoria;
        partial void OnIdCategoriaChanging(global::System.Int32 value);
        partial void OnIdCategoriaChanged();

        #endregion
    
        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Produto_Categoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("VendasModel.FK_Produto_Categoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("VendasModel.FK_Produto_Categoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("VendasModel.FK_Produto_Categoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("VendasModel.FK_Produto_Categoria", "Categoria", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
